# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"/\n\x13GetUserByIdResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\",\n\x18GetUserByUsernameRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"5\n\x19GetUserByUsernameResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"F\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\".\n\x12\x43reateUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"I\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x14\n\x0c\x63reated_time\x18\x04 \x01(\t2\xe8\x01\n\x0bUserService\x12\x42\n\x0bGetUserById\x12\x18.user.GetUserByIdRequest\x1a\x19.user.GetUserByIdResponse\x12T\n\x11GetUserByUsername\x12\x1e.user.GetUserByUsernameRequest\x1a\x1f.user.GetUserByUsernameResponse\x12?\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETUSERBYIDREQUEST']._serialized_start=20
  _globals['_GETUSERBYIDREQUEST']._serialized_end=52
  _globals['_GETUSERBYIDRESPONSE']._serialized_start=54
  _globals['_GETUSERBYIDRESPONSE']._serialized_end=101
  _globals['_GETUSERBYUSERNAMEREQUEST']._serialized_start=103
  _globals['_GETUSERBYUSERNAMEREQUEST']._serialized_end=147
  _globals['_GETUSERBYUSERNAMERESPONSE']._serialized_start=149
  _globals['_GETUSERBYUSERNAMERESPONSE']._serialized_end=202
  _globals['_CREATEUSERREQUEST']._serialized_start=204
  _globals['_CREATEUSERREQUEST']._serialized_end=274
  _globals['_CREATEUSERRESPONSE']._serialized_start=276
  _globals['_CREATEUSERRESPONSE']._serialized_end=322
  _globals['_USER']._serialized_start=324
  _globals['_USER']._serialized_end=397
  _globals['_USERSERVICE']._serialized_start=400
  _globals['_USERSERVICE']._serialized_end=632
# @@protoc_insertion_point(module_scope)
