"""init_products_and_seckill

Revision ID: 808ae1d11a47
Revises: 
Create Date: 2026-03-31 16:31:07.018436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '808ae1d11a47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='商品名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='商品描述'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='商品原价'),
    sa.Column('stock', sa.Integer(), nullable=True, comment='商品总库存'),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seckill_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='关联商品ID'),
    sa.Column('seckill_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='秒杀价格'),
    sa.Column('seckill_stock', sa.Integer(), nullable=False, comment='秒杀库存'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='秒杀开始时间'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='秒杀结束时间'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态：1-未开始，2-进行中，3-已结束'),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seckill_activities')
    op.drop_table('products')
    # ### end Alembic commands ###
